# Generated by Django 2.2.5 on 2019-11-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
