# Generated by Django 2.2.5 on 2019-11-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='message',
            new_name='request_message',
        ),
        migrations.AddField(
            model_name='request',
            name='response_message',
            field=models.TextField(default=''),
        ),
    ]
