# Generated by Django 2.2.5 on 2019-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20191109_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='active',
            field=models.CharField(default='True', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
